# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    MAKEFILE                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: gd-hallu <gd-hallu@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2026/05/18 23:16:53 by gd-hallu          #+#    #+#              #
#    Updated: 2026/05/18 23:32:02 by gd-hallu         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# ------------------ PROJECT NAME ----------------- #
NAME			:= minishell

# ------------------- CONSTANTS ------------------- #
CC				:= cc
MKDIRP			:= mkdir -p
RMRF			:= rm -rf
RMF				:= rm -f
MODE			:= debug_memory

# ------------------- DIRECTORIES ----------------- #
HDR				:= include
OBJ				:= obj
SRC				:= src
ASM				:= asm

# ------------------- COMPILER -------------------- #
ifeq ($(findstring clang, $(shell $(CC) --version)), clang)
	COMPILER		:= clang
else ifeq ($(findstring gcc, $(shell $(CC) --version)), gcc)
	COMPILER		:= gcc
else
	@echo "Your device require clang or gnu compilator to run the program"
	@exit 1
endif

# --------------------- FLAGS --------------------- #
ifeq ($(COMPILER), clang)
	W_FLAGS			:= 	-Wall -Werror -Wextra -Wvla -Wpedantic -pedantic-errors -Wmisleading-indentation \
						-Wsign-conversion -Wshadow -Wnull-dereference -fshort-enums
else
	W_FLAGS			:= 	-Wall -Werror -Wextra -Wvla -Wpedantic -pedantic-errors -Wmisleading-indentation \
					-Wsign-conversion -Wstrict-aliasing=3 -Wduplicated-cond -Wstringop-overflow -Wshadow\
					-Wnull-dereference -Warray-bounds -Wrestrict -Wconversion
endif

ifeq (debug_memory, $(MODE))
	C_FLAGS			:= -fsanitize=address -fsanitize=undefined -g -O1 -march=native -std=c11
else ifeq (debug_thread, $(MODE))
	C_FLAGS			:= -fsanitize=thread -g -O1 -march=native -std=c11
else ifeq (release, $(MODE))
	C_FLAGS			:= -g -O3 -march=native -std=c11
else
	@echo "Your device require clang or gnu compilator to run the program"
	@exit 1
endif

# --------------------- FILES --------------------- #
SOURCES 			:=

# -------------------- OBJECTS -------------------- #
OBJECTS 			:= $(patsubst $(SRC)/%.c, $(OBJ)/%.o, $(SOURCES))

# ---------------- COMPILATION RULES -------------- #
all: $(NAME)

$(NAME): $(OBJECTS)
	$(CC) $(W_FLAGS) $(C_FLAGS) $(OBJECTS) -I$(HDR) -o $(NAME)

$(OBJ)/%.o: $(SRC)/%.c | $(OBJ)
	$(CC) $(W_FLAGS) $(C_FLAGS) -I$(HDR) -c $< -o $@

$(OBJ):
	$(MKDIRP) $@

# ------------------ CLEAN UP RULES --------------- #
clean:
	$(RMRF) $(OBJ)

fclean: clean
	$(RMF) $(NAME)

re: fclean all

.PHONY: all re fclean clean